### ISSUE TITLE
changing demo night status will allow more than 1 to be active

### ISSUE THREAD

**Issue by notmarkmiranda** [s-espinosa/demonight#61]

**Comment by s-espinosa** [comment]
@notmarkmiranda Can you provide some more info? Isn't this already caught with the `before_action` on `demo_nights_controller#create`?

Are you talking about if we move something from closed back to an active status? I can see how that would pretty much make everything blow up. Currently we don't have any way to bring a DemoNight back from closed in the application itself. We can do it in the console, but not in the `index`, or `show`.

In some ways I think that it's o.k. for someone who has access to the console to make this kind of change, with the understanding that such a person would need to know that this could kill the app, but I guess as I type that it seems like maybe we would want to protect against even that.

Thoughts on a best way to do it? A second `before_action` attached to `demo_nights_controller#update`? It would need to check to see if there was a current demo night and then also to check that you were trying to bring something back from `closed`. Otherwise we would just be killing `#update`. Other thoughts?

**Comment by notmarkmiranda** [comment]
I'm referencing the update from closed to active status. There is a way to do that `admin/demo_nights` can do that. That's where I originally realized that it's doable.

Yeah, I would think a before_action on update would be the way to go.

Mainly just wanted to make a note of it so I didn't forget.

**Comment by s-espinosa** [comment]
As part of this, recommend that we also change the button behavior on the index to match that on the show. Currently the index allows you to move things back and forth (though I don't believe you can move it from closed), while the show only allows you to move forward. Let me know what you think.

**Comment by notmarkmiranda** [comment]
on board with making things consistent on both.
